import { AntiPortfolioData } from '../types';

declare global {
  interface Window {
    html2pdf: any;
  }
}

export const downloadJSON = (data: AntiPortfolioData) => {
  const jsonString = JSON.stringify(data, null, 2);
  const blob = new Blob([jsonString], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `impact-lens-${data.meta.viewer}-${new Date().toISOString().split('T')[0]}.json`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const generateMarkdown = (data: AntiPortfolioData): string => {
  return `
# ${data.headline}

**Lens:** ${data.meta.viewer.toUpperCase()}
**Confidence:** ${data.confidence.overall.toUpperCase()}
**Version:** ${data.meta.version}

---

## EXECUTIVE SUMMARY
${data.diagnosis_summary.map(s => `- ${s}`).join('\n')}

### ${data.viewer_lens_section.title.toUpperCase()}
${data.viewer_lens_section.bullets.map(b => `- ${b}`).join('\n')}

---

## SYSTEMIC EFFECTS TIMELINE
${data.systemic_effects_timeline.map(t => `
### ${t.horizon.replace('_', ' ').toUpperCase()}
${t.effects.map(e => `- **${e.claim}**\n  *Evidence: ${e.evidence.join(', ')}*`).join('\n')}
`).join('\n')}

---

## CONTEXTS

### Best Fit
${data.best_fit_contexts.map(c => `- **${c.context}**: ${c.why}\n  *Evidence: ${c.evidence.join(', ')}*`).join('\n')}

### Toxic Contexts
${data.toxic_contexts.map(c => `- **${c.context}**: ${c.failure_pattern}\n  *Evidence: ${c.evidence.join(', ')}*`).join('\n')}

---

## FAILURE MODES
${data.failure_modes.map(m => `
### ${m.mode}
- **Trigger:** ${m.trigger}
- **Symptom:** ${m.symptom}
- **Mitigation:** ${m.mitigation}
`).join('\n')}

---

## TRADE-OFFS
${data.tradeoffs.map(t => `- **${t.tradeoff}**\n  - Upside: ${t.upside}\n  - Cost: ${t.cost}`).join('\n')}

---

## FLAGS & VALIDATION

### Don't Work With Me If...
${data.dont_work_with_me_if.map(i => `- ${i}`).join('\n')}

### Proof Hooks
${data.proof_hooks.map(h => `- **${h.claim_to_validate}**\n  Verify: ${h.how_to_check}`).join('\n')}

---

*Generated by Impact Lens AI Diagnostic Engine*
`.trim();
};

export const downloadMarkdown = (data: AntiPortfolioData) => {
  const mdString = generateMarkdown(data);
  const blob = new Blob([mdString], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `impact-lens-${data.meta.viewer}-${new Date().toISOString().split('T')[0]}.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const downloadPDF = (elementId: string, filename: string) => {
  const element = document.getElementById(elementId);
  if (!element) {
    console.error(`Element with id ${elementId} not found`);
    return;
  }

  // Check if html2pdf is loaded
  if (typeof window.html2pdf === 'undefined') {
    alert("PDF generator library is not loaded. Please wait or refresh.");
    return;
  }

  // Clone the element to isolate it from the current page layout (scrolls, margins, etc.)
  // This prevents blank pages caused by window.scrollY or parent padding.
  const clone = element.cloneNode(true) as HTMLElement;
  
  // Style the clone for the PDF output
  clone.style.width = '1200px'; // Fixed width to ensure consistent layout
  clone.style.maxWidth = '1200px';
  clone.style.padding = '40px';
  clone.style.backgroundColor = '#ffffff'; // Ensure white background
  clone.style.margin = '0 auto';
  
  // Remove any display:none elements or scripts from clone if necessary
  const noPrints = clone.querySelectorAll('.no-print');
  noPrints.forEach(el => el.remove());

  // Create a temporary container to hold the clone
  const container = document.createElement('div');
  container.style.position = 'absolute';
  container.style.top = '0';
  container.style.left = '0';
  container.style.zIndex = '-9999'; // Hide behind everything
  container.style.width = '1200px'; 
  container.appendChild(clone);
  document.body.appendChild(container);

  const opt = {
    margin: [10, 10], // top/bottom margin in mm
    filename: filename,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: { 
      scale: 2, // 2x scale for retina-like quality
      useCORS: true,
      logging: false,
      scrollY: 0, // CRITICAL: prevents capturing blank space above if user scrolled down
      windowWidth: 1200, // CRITICAL: ensures media queries match the clone width
    },
    jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
    pagebreak: { mode: ['avoid-all', 'css', 'legacy'] }
  };

  // Generate PDF from the clone, then clean up
  window.html2pdf().set(opt).from(clone).save().then(() => {
    document.body.removeChild(container);
  });
};
