import { AntiPortfolioData } from '../types';

export const downloadJSON = (data: AntiPortfolioData) => {
  const jsonString = JSON.stringify(data, null, 2);
  const blob = new Blob([jsonString], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `impact-lens-${data.meta.viewer}-${new Date().toISOString().split('T')[0]}.json`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const downloadHTML = (filename: string) => {
  const element = document.getElementById('diagnostic-report-content');
  if (!element) return;

  const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${filename}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500&family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <script>
      tailwind.config = {
        theme: {
          extend: {
            fontFamily: {
              sans: ['Inter', 'sans-serif'],
              mono: ['JetBrains Mono', 'monospace'],
            },
            colors: {
              brand: {
                50: '#eef2ff',
                100: '#e0e7ff',
                500: '#6366f1',
                600: '#4f46e5',
                700: '#4338ca',
                900: '#312e81',
              },
              slate: {
                850: '#1e293b',
                900: '#0f172a',
              }
            },
            boxShadow: {
              'soft': '0 4px 20px -2px rgba(0, 0, 0, 0.05)',
              'glow': '0 0 15px rgba(79, 70, 229, 0.3)',
            }
          }
        }
      }
    </script>
    <style>
      body { background-color: white; color: #0f172a; -webkit-font-smoothing: antialiased; padding: 40px; }
      .break-inside-avoid { break-inside: avoid; }
      /* Hide print-only elements that might have been copied */
      .no-print { display: none !important; }
    </style>
</head>
<body>
    <div class="max-w-5xl mx-auto">
        ${element.innerHTML}
    </div>
</body>
</html>`;

  const blob = new Blob([htmlContent], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `${filename}.html`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const generateMarkdown = (data: AntiPortfolioData): string => {
  return `
# ${data.headline}

**Lens:** ${data.meta.viewer.toUpperCase()}
**Confidence:** ${data.confidence.overall.toUpperCase()}
**Version:** ${data.meta.version}

---

## EXECUTIVE SUMMARY
${data.diagnosis_summary.map(s => `- ${s}`).join('\n')}

### ${data.viewer_lens_section.title.toUpperCase()}
${data.viewer_lens_section.bullets.map(b => `- ${b}`).join('\n')}

---

## SYSTEMIC EFFECTS TIMELINE
${data.systemic_effects_timeline.map(t => `
### ${t.horizon.replace('_', ' ').toUpperCase()}
${t.effects.map(e => `- **${e.claim}**\n  *Evidence: ${e.evidence.join(', ')}*`).join('\n')}
`).join('\n')}

---

## CONTEXTS

### Best Fit
${data.best_fit_contexts.map(c => `- **${c.context}**: ${c.why}\n  *Evidence: ${c.evidence.join(', ')}*`).join('\n')}

### Toxic Contexts
${data.toxic_contexts.map(c => `- **${c.context}**: ${c.failure_pattern}\n  *Evidence: ${c.evidence.join(', ')}*`).join('\n')}

---

## FAILURE MODES
${data.failure_modes.map(m => `
### ${m.mode}
- **Trigger:** ${m.trigger}
- **Symptom:** ${m.symptom}
- **Mitigation:** ${m.mitigation}
`).join('\n')}

---

## TRADE-OFFS
${data.tradeoffs.map(t => `- **${t.tradeoff}**\n  - Upside: ${t.upside}\n  - Cost: ${t.cost}`).join('\n')}

---

## FLAGS & VALIDATION

### Don't Work With Me If...
${data.dont_work_with_me_if.map(i => `- ${i}`).join('\n')}

### Proof Hooks
${data.proof_hooks.map(h => `- **${h.claim_to_validate}**\n  Verify: ${h.how_to_check}`).join('\n')}

---

*Generated by Impact Lens AI Diagnostic Engine*
`.trim();
};

export const downloadMarkdown = (data: AntiPortfolioData) => {
  const mdString = generateMarkdown(data);
  const blob = new Blob([mdString], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `impact-lens-${data.meta.viewer}-${new Date().toISOString().split('T')[0]}.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
